# Generated by Django 6.1.1 on 2026-09-11 17:12

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventarioVulnerabilidade',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('categoria', models.CharField(help_text='Ex: Encosta, Árvore Podre, Bueiro Entupido', max_length=150)),
                ('prioridade_acao', models.CharField(choices=[('P1', 'P1 - Imediata (Emergência)'), ('P2', 'P2 - Alta (Risco Iminente)'), ('P3', 'P3 - Programada (Manutenção)'), ('P4', 'P4 - Acompanhamento Mensal'), ('P5', 'P5 - Observação Sazonal')], max_length=2)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
                ('data_vistoria', models.DateTimeField(auto_now_add=True)),
                ('secretaria_responsavel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='usuarios.secretaria')),
            ],
            options={
                'verbose_name': 'Vulnerabilidade (MMVC)',
                'verbose_name_plural': 'Inventário MMVC',
            },
        ),
    ]
