# Generated by Django 6.1.1 on 2026-09-11 17:24

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ocorrencias', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ocorrencia',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('categoria', models.CharField(help_text='Ex: Árvore Caída na Pista, Alagamento', max_length=150)),
                ('prioridade_acao', models.CharField(choices=[('P1', 'P1 - Imediata (Emergência)'), ('P2', 'P2 - Alta (Risco Iminente)'), ('P3', 'P3 - Programada (Manutenção)'), ('P4', 'P4 - Acompanhamento Mensal'), ('P5', 'P5 - Observação Sazonal')], max_length=2)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
                ('foto_storage_url', models.URLField(blank=True, help_text='Link da foto no R2', max_length=500, null=True)),
                ('status_publico', models.CharField(choices=[('Recebido', 'Recebido pela Prefeitura'), ('Em Atendimento', 'Equipe em Deslocamento / Em Atendimento'), ('Concluido', 'Ocorrência Resolvida')], default='Recebido', max_length=50)),
                ('status_interno', models.CharField(blank=True, help_text='Ex: Aguardando motosserra.', max_length=255, null=True)),
                ('data_registro', models.DateTimeField(auto_now_add=True)),
                ('vulnerabilidade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ocorrencias.inventariovulnerabilidade')),
            ],
            options={
                'verbose_name': 'Ocorrência (Desastre)',
                'verbose_name_plural': 'Ocorrências Abertas',
            },
        ),
    ]
