# Generated by Django 6.1.1 on 2026-09-14 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ocorrencias', '0003_ocorrencia_bairro_ocorrencia_descricao_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ocorrencia',
            name='logradouro',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='ocorrencia',
            name='numero',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
