# Generated by Django 6.1.1 on 2026-09-15 01:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ocorrencias', '0004_ocorrencia_logradouro_ocorrencia_numero'),
        ('usuarios', '0003_perfilusuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='ocorrencia',
            name='secretaria_responsavel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ocorrencias_atribuidas', to='usuarios.secretaria'),
        ),
    ]
