# Generated by Django 6.1.1 on 2026-09-15 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ocorrencias', '0005_ocorrencia_secretaria_responsavel'),
    ]

    operations = [
        migrations.AddField(
            model_name='ocorrencia',
            name='relatorio_resolucao',
            field=models.TextField(blank=True, help_text='Como a ocorrência foi solucionada pela equipe.', null=True, verbose_name='Relatório de Resolução'),
        ),
    ]
