# Generated by Django 6.1.1 on 2026-09-11 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EstacaoMeteorologica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Ex: Estação Escola Municipal X', max_length=150)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=10)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=10)),
                ('ativa', models.BooleanField(default=True, help_text='Desmarque se a estação quebrar no meio da tempestade')),
            ],
            options={
                'verbose_name': 'Estação Meteorológica',
                'verbose_name_plural': 'Estações Meteorológicas',
            },
        ),
        migrations.CreateModel(
            name='SistemaEstado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nivel_operacional', models.IntegerField(choices=[(0, 'Nível 0 - Normalidade'), (1, 'Nível 1 - Atenção'), (2, 'Nível 2 - Alerta'), (3, 'Nível 3 - Alerta Máximo'), (4, 'Nível 4 - Recuperação')], default=0)),
                ('alterado_em', models.DateTimeField(auto_now=True)),
                ('mensagem_alerta', models.TextField(blank=True, help_text='Mensagem que vai aparecer no celular de todos os cidadãos.', null=True)),
            ],
            options={
                'verbose_name': 'Controle de Nível (Prefeito)',
                'verbose_name_plural': 'Controle de Nível (Prefeito)',
            },
        ),
    ]
