# Generated by Django 6.1.1 on 2026-09-14 13:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clima', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeituraEstacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_hora', models.DateTimeField(auto_now_add=True, help_text='Momento exato em que a leitura chegou')),
                ('chuva_mm', models.DecimalField(blank=True, decimal_places=2, help_text='Volume de chuva em mm', max_digits=5, null=True)),
                ('nivel_rio_metros', models.DecimalField(blank=True, decimal_places=2, help_text='Nível do rio em metros', max_digits=5, null=True)),
                ('temperatura_c', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('estacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leituras', to='clima.estacaometeorologica')),
            ],
            options={
                'verbose_name': 'Leitura da Estação',
                'verbose_name_plural': 'Leituras das Estações',
                'ordering': ['-data_hora'],
            },
        ),
    ]
