# Generated by Django 6.1.1 on 2026-09-14 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='secretaria',
            name='email_oficial',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='E-mail Oficial'),
        ),
        migrations.AddField(
            model_name='secretaria',
            name='nome_ponto_focal',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Nome do Ponto Focal'),
        ),
        migrations.AddField(
            model_name='secretaria',
            name='recursos_estrategicos',
            field=models.TextField(blank=True, help_text='Ex: Caminhão pipa, abrigos, retroescavadeira', null=True),
        ),
        migrations.AddField(
            model_name='secretaria',
            name='sigla',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Sigla'),
        ),
        migrations.AddField(
            model_name='secretaria',
            name='telefone_plantao',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Telefone de Plantão (24h)'),
        ),
        migrations.AddField(
            model_name='secretaria',
            name='telefone_ponto_focal',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Telefone do Ponto Focal'),
        ),
    ]
