# Generated by Django 6.1.1 on 2026-09-15 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_solicitacaoacesso'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitacaoacesso',
            name='senha_provisoria',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
