# Generated by Django 6.1.1 on 2026-09-16 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0005_solicitacaoacesso_senha_provisoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='secretaria',
            name='cor_identidade',
            field=models.CharField(default='#022888', max_length=20, verbose_name='Cor de Identidade (Hex)'),
        ),
    ]
